spring:
  datasource:
    url: jdbc:h2:file:~/h2/editor;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: root
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
      show-sql: true

server:
  port: 8500

logging:
  level:
    com.reverb: debug